# Generated by Django 6.0 on 2025-12-25 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_workout_ended_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutset',
            name='rpe',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='workoutset',
            name='set_type',
            field=models.CharField(choices=[('W', 'Warm-up'), ('S', 'Standard'), ('F', 'Failure'), ('D', 'Drop Set')], default='S', max_length=1),
        ),
    ]
