# Generated by Django 6.0 on 2025-12-25 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_workoutset_rpe_workoutset_set_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutset',
            name='is_abs_weight_pr',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workoutset',
            name='is_e1rm_pr',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workoutset',
            name='is_rep_pr',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workoutset',
            name='is_volume_pr',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workoutset',
            name='unit',
            field=models.CharField(choices=[('lbs', 'Pounds'), ('kg', 'Kilograms')], default='lbs', max_length=3),
        ),
    ]
