# Generated by Django 6.0 on 2026-01-03 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_workoutset_is_abs_weight_pr_workoutset_is_e1rm_pr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='custom',
            field=models.BooleanField(default=False),
        ),
    ]
