# Generated by Django 6.0 on 2026-01-06 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0006_passwordresetcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardioSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_number', models.PositiveIntegerField()),
                ('mode', models.CharField(choices=[('TREADMILL', 'Treadmill'), ('BIKE', 'Stationary Bike'), ('ELLIPTICAL', 'Elliptical Trainer'), ('STAIRS', 'Stair Climber'), ('ROW', 'Rowing Machine')], max_length=16)),
                ('duration_seconds', models.PositiveIntegerField(help_text='Total duration in seconds')),
                ('distance_meters', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('floors', models.PositiveIntegerField(blank=True, null=True)),
                ('level', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('split_seconds', models.DecimalField(blank=True, decimal_places=2, help_text='Split time in seconds per 500m', max_digits=6, null=True)),
                ('spm', models.DecimalField(blank=True, decimal_places=1, help_text='Strokes per minute', max_digits=5, null=True)),
                ('is_pr', models.BooleanField(default=False)),
                ('is_distance_pr', models.BooleanField(default=False)),
                ('is_pace_pr', models.BooleanField(default=False)),
                ('is_ascent_pr', models.BooleanField(default=False)),
                ('is_intensity_pr', models.BooleanField(default=False)),
                ('is_split_pr', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cardio_sets', to='workouts.exercise')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cardio_sets', to='workouts.workout')),
            ],
            options={
                'ordering': ['workout', 'set_number'],
                'unique_together': {('workout', 'exercise', 'set_number')},
            },
        ),
    ]
